name: omniQTL
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - setuptools=80.9.0
  - numpy=2.4.1
  - pandas=3.0.0
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - plink=1.90b7.7
  - plink2=2.0.0a.6.9
  - bcftools=1.22
  - perl
  - pip
  - pip:
      - -r requirements.txt
      - -e .
