from .utils import *
from .qc import ArrayQC

class Genotyping(ArrayQC):
    def __init__(self, bfile='TIGER'):
        super().__init__()
        self.bfile = bfile
        self.output_prefix = f'{self.bfile}_QCed'
        self.chroms = [f'chr{n}' for n in range(1, 23)]

    def pre_imputation_check(self, pre_imputation_check_script=None, ref_file=None, ref_name='1000g', pop='ALL', update_script='Run-plink.sh'):
        if pre_imputation_check_script is None:
            pre_imputation_check_script = str(BASE.parent.parent / 'vendor/pre_imputation_check/HRC-1000G-check-bim.pl')
        if ref_file is None:
            ref_file = str(BASE.parent.parent / 'vendor/pre_imputation_check/1000GP_Phase3_combined.legend')

        out_dir = f'{self.output_prefix}_checked'
        if os.path.exists(pre_imputation_check_script) and os.path.exists(ref_file):
            cmd = f'plink --bfile {self.output_prefix} --freq --out {self.output_prefix}'
            subprocess.run(cmd, shell=True)
            cmd = f'perl {pre_imputation_check_script} --bim {self.output_prefix}.bim --frequency {self.output_prefix}.frq -r {ref_file} --{ref_name} --pop {pop} --out {out_dir}'
            subprocess.run(cmd, shell=True)
            run_script_path = f'{out_dir}/{update_script}'
            if os.path.exists(run_script_path):
                cmd = f'bash {run_script_path}'
                subprocess.run(cmd, shell=True)
            else:
                raise FileNotFoundError(f"Run script generated by pre-imputation check not found at {run_script_path}")
        else:
            raise FileNotFoundError(f"Pre-imputation check script or reference file not found")

        if not os.path.exists(out_dir):
            raise FileNotFoundError(f"Output directory {out_dir} not found after pre-imputation check")
        
        vcfs = sorted([f'{out_dir}/{f}' for f in os.listdir(out_dir) if f.endswith('.vcf')])
        for vcf in vcfs:
            cmd = f'bgzip {vcf}; tabix -p vcf {vcf}.gz'
            print(cmd)
            subprocess.run(cmd, shell=True)

    def submit_to_topmed(self, config_file='config.yaml', job_name=None):
        if job_name is None:
            job_name = f'{self.bfile}'
        in_dir = f'{self.output_prefix}_checked'
        if not os.path.exists(in_dir):
            raise FileNotFoundError(f"Input directory {in_dir} not found")
        cwd = os.getcwd()
        os.chdir(in_dir)
        vcfs = sorted([f for f in os.listdir('.') if f.endswith('.vcf.gz') and f.split('.vcf.gz')[0].split('-')[-1] in self.chroms])

        if os.path.exists(config_file):
            with open(config_file, 'r') as f:
                config = yaml.safe_load(f)
        else:
            config_file = str(BASE / 'config' / config_file)
            config_template = str(BASE / 'config/config_template.yaml') 
            if os.path.exists(config_file):
                with open(config_file, 'r') as f:
                    config = yaml.safe_load(f)
            else:
                raise FileNotFoundError(f"Config file not found. Please provide one with reference to the template: {config_template}")

        try:
            url = config['TOPMed']['url']
            version = config['TOPMed']['version']
            token = config['TOPMed']['token']
            refpanel = config['TOPMed']['refpanel']
            population = config['TOPMed']['population']
            phasing = config['TOPMed']['phasing']
            cmd = f'curl {url}@{version} -H "X-Auth-Token: {token}" -F "refpanel={refpanel}" -F "job-name={job_name}" -F "population={population}" -F "input-phasing={phasing}" '
            for vcf in vcfs:
                cmd += f'-F "files=@{vcf}" '
            print(cmd)
            subprocess.run(cmd, shell=True)

        except Exception as e:
            raise KeyError(f"Missing required TOPMed configuration parameters: {e}")
        os.chdir(cwd)

    def get_topmed_results(self, cmd, password, out_dir=None, exclude_typed_only_variants=True, n_threads=4):
        if out_dir is None:
            out_dir = f'{self.bfile}_TOPMed'
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)
        cwd = os.getcwd()
        os.chdir(out_dir)
        subprocess.run(cmd, shell=True)

        fs = [f for f in os.listdir('.') if f.find('chr') == 0 and f.endswith('.zip')]
        for f in fs:
            cmd = f'unzip -P "{password}" {f}'
            subprocess.run(cmd, shell=True)

        vcfs = []
        for ch in self.chroms:
            f = f'{ch}.dose.vcf.gz'
            cmd = f'tabix -p vcf {f}'
            if os.path.exists(f):
                subprocess.run(cmd, shell=True)
                vcfs.append(f)
            else:
                print(f"Warning: Expected VCF file {f} not found in TOPMed results")

        in_file = f'{self.bfile}_concated.vcf.gz'
        out_file = f'{self.bfile}_imputed.vcf.gz'
        cmd = f'bcftools concat --threads {n_threads} {" ".join(vcfs)} -Oz -o {in_file}; tabix -p vcf {in_file}'
        subprocess.run(cmd, shell=True)
        if exclude_typed_only_variants:
            cmd = f'''bcftools view -i 'INFO/IMPUTED=1' --threads {n_threads} {in_file} -Oz -o {out_file}; tabix -p vcf {out_file}'''
            subprocess.run(cmd, shell=True)
        else:
            os.rename(in_file, out_file)
            os.rename(in_file + '.tbi', out_file + '.tbi')

        cmd = f'plink2 --vcf {out_file} --make-bed --out {out_file.split(".vcf")[0]}'
        subprocess.run(cmd, shell=True)
        os.chdir(cwd)

    def merge_vcfs(self, vcf_files, output_vcf, n_threads=4, params={'R2':'avg'}):
        params_str = ','.join([f'{key}:{value}' for key, value in params.items()])
        if params_str:
            params_str = f'-i {params_str}'
        cmd = f'bcftools merge -Oz -o {output_vcf} --threads {n_threads} {params_str} {" ".join(vcf_files)}; tabix -p vcf {output_vcf}'
        subprocess.run(cmd, shell=True)

    def subset_samples_vcf(self, vcf_file, sample_list, output_vcf, n_threads=4):
        cmd = f'bcftools view --threads {n_threads} -S {sample_list} {vcf_file} -Oz -o {output_vcf}; tabix -p vcf {output_vcf}'
        print(cmd)
        subprocess.run(cmd, shell=True)

    def rename_samples_vcf(self, vcf_file, sample_mapping_file, sort_samples=True, n_thresholds=4):
        out_file = vcf_file.replace('.vcf.gz', '_sampleRenamed.vcf.gz')
        cmd = f'bcftools reheader -s {sample_mapping_file} {vcf_file} -o {out_file}; tabix -p vcf {out_file}'
        subprocess.run(cmd, shell=True)
        if sort_samples:
            out_file_tmp = out_file.replace('.vcf.gz', '_tmp.vcf.gz')
            samples_sorted = out_file.replace('.vcf.gz', '_samples_sorted.txt')
            cmd = f'bcftools query -l {out_file}| sort > {samples_sorted}'
            subprocess.run(cmd, shell=True)
            cmd = f'bcftools view --threads {n_thresholds} -S {samples_sorted} {out_file} -Oz -o {out_file_tmp}; tabix -p vcf {out_file_tmp}'
            subprocess.run(cmd, shell=True)
            os.rename(out_file_tmp, out_file)
            os.rename(f'{out_file_tmp}.tbi', f'{out_file}.tbi')

    def annotate_variants_vcf(self, vcf_file, dbsnp_vcf='dbSNP_hg38.gz', ref_fa='hg38.fa', norm_variants=True, dbsnp_url='https://ftp.ncbi.nih.gov/snp/latest_release/VCF/', id_col='ID', id_name=r'%CHROM\_%POS\_%REF\_%FIRST_ALT', n_threads=4):
        if not os.path.exists(dbsnp_vcf):
            raise FileNotFoundError(f"dbSNP VCF file not found at {dbsnp_vcf}")

        if not os.path.exists(dbsnp_vcf):
            raise FileNotFoundError(f"Reference FASTA file not found at {ref_fa}")

        out_file_norm = vcf_file.split('.vcf')[0] + '_norm.vcf.gz'
        out_file_rs = vcf_file.split('.vcf')[0] + '_rs.vcf.gz'
        out_file_rsID = vcf_file.split('.vcf')[0] + '_rsID.vcf.gz'

        if norm_variants:
            cmd = f'bcftools norm --threads {n_threads} -f {ref_fa} -m -any {vcf_file} -Oz -o {out_file_norm}; tabix -p vcf {out_file_norm}'
            subprocess.run(cmd, shell=True)
            vcf_file = out_file_norm

        cmd = f'bcftools annotate --threads {n_threads} -a {dbsnp_vcf} -c {id_col} -Oz -o {out_file_rs} {vcf_file}'
        subprocess.run(cmd, shell=True)

        cmd = f"bcftools annotate --threads {n_threads} --set-id +'{id_name}' {out_file_rs} -Oz -o {out_file_rsID}; tabix -p vcf {out_file_rsID}"
        subprocess.run(cmd, shell=True)
        os.remove(out_file_rs)

    def filter_variants_vcf(self, vcf_file, output_vcf=None, params={'update_flags':['AC', 'AN', 'AF', 'MAF'], 'MAF':0.05, 'R2':0.8}, n_threads=4):
        if output_vcf is None:
            output_vcf = vcf_file.replace('.vcf.gz', '_variantFiltered.vcf.gz')

        vcf_file_tmp = vcf_file
        cmd = ''
        expr = ''
        if 'MAF' in params and 'R2' in params:
            expr = f"MAF>{params['MAF']} && R2>{params['R2']}"
        elif 'MAF' in params:
            expr = f"MAF>{params['MAF']}"
        elif 'R2' in params:
            expr = f"R2>{params['R2']}"

        if 'update_flags' in params:
            flags = ','.join([f'{flag}' for flag in params['update_flags']])
            cmd = f'''bcftools +fill-tags --threads {n_threads} {vcf_file} -Ou -- -t {flags} | '''
            vcf_file_tmp = ''
        cmd  += f'''bcftools filter --threads {n_threads} -i "{expr}" {vcf_file_tmp} -Oz -o {output_vcf}'''
        print(cmd)
        subprocess.run(cmd, shell=True)
        cmd = f'tabix -p vcf {output_vcf}'
        subprocess.run(cmd, shell=True)

    def vcf_to_bfile(self, vcf_file):
        bfile = vcf_file.split('.vcf')[0]
        cmd = f'plink2 --vcf {vcf_file} --make-bed --out {bfile}'
        subprocess.run(cmd, shell=True)
